# version: '3.8'
# services:
#   php-apache-environment:
#     container_name: php-docker-container
#     build:
#       dockerfile: Dockerfile
#     volumes:
#       - ./src:/var/www/html/
#     ports:
#       - 8000:80

version: '3.7'
services:
  nexus:
    image: sonatype/nexus3
    expose:
      - 8081
    ports:
      - "8081:8081"
    volumes:
      - ./src:/var/www/html/  
